#!/usr/bin/env bash
old_stash=$(git rev-parse -q --verify refs/stash)
git stash save -q --keep-index
new_stash=$(git rev-parse -q --verify refs/stash)

if [ "$old_stash" = "$new_stash" ]; then
  echo "pre-commit script: no changes to test"
  sleep 1
  exit 0
fi

make check
status=$?

git reset --hard -q && git stash apply --index -q && git stash drop -q
exit $status
